//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jewelleryonpc {
    
    public partial class AppMaster {
        protected System.Web.UI.HtmlControls.HtmlForm mainForm;
        protected System.Web.UI.WebControls.HyperLink lnkHome;
        protected System.Web.UI.WebControls.Label lblSearch;
        protected System.Web.UI.WebControls.TextBox txtSearch;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.SiteMapDataSource sitemap;
        protected System.Web.UI.WebControls.Menu mainmenu;
        protected System.Web.UI.WebControls.SiteMapPath smPath;
        protected System.Web.UI.WebControls.ContentPlaceHolder mainCopy;
        protected System.Web.UI.WebControls.SiteMapDataSource subnavSitemap;
        protected System.Web.UI.WebControls.Menu subMenu;
        protected System.Web.UI.WebControls.ContentPlaceHolder leftColumn;
        protected System.Web.UI.WebControls.Image Image1;
        protected System.Web.UI.WebControls.HyperLink HyperLink7;
        protected System.Web.UI.WebControls.HyperLink hyperlink1;
        protected System.Web.UI.WebControls.HyperLink hyperlink2;
        protected System.Web.UI.WebControls.HyperLink hyperlink3;
        protected System.Web.UI.WebControls.HyperLink hyperlink4;
        protected System.Web.UI.WebControls.HyperLink hyperlink5;
        protected System.Web.UI.WebControls.HyperLink hyperlink6;
        protected System.Web.UI.WebControls.Login Login1;
        protected System.Web.UI.WebControls.ContentPlaceHolder rightColumn;
        protected System.Web.UI.WebControls.HyperLink HyperLink8;
        protected System.Web.UI.WebControls.Image TopazPearImage;
        protected System.Web.UI.WebControls.HyperLink HyperLink9;
    }
}
