//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jewelleryonpc.Buy {
    
    public partial class Buy_Default {
        protected System.Web.UI.WebControls.ImageButton Button2;
        protected System.Web.UI.WebControls.ImageButton ImageButton1;
    }
}
